name: nursultan_app
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  dio: ^5.3.3
  logging: ^1.2.0
  tf_dio_cache: ^1.0.2
  get_it: ^7.6.4
  json_annotation: ^4.6.0
  location: ^5.0.3
  background_locator_2: ^2.0.6
  location_permissions: ^4.0.1


  # riverpod
  hooks_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  flutter_hooks: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_generator: ^2.2.3
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  build_runner: ^2.4.6


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
